db:
  image: mysql:5.7
  environment:
    MYSQL_DATABASE: aion
    MYSQL_USER: aion 
    MYSQL_PASSWORD: aion
    MYSQL_ROOT_PASSWORD: aion
  ports:
    - "3306"

nsqlookupd:
  image: nsqio/nsq:v0.3.5
  command: /nsqlookupd
  ports:
    - "4160:4160"
    - "4161:4161"

nsqadmin:
  image: nsqio/nsq:v0.3.5
  command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
  links:
    - nsqlookupd
    - nsqd
  ports:
    - "4171:4171"

nsqd:
  image: nsqio/nsq:v0.3.5
  volumes:
    - /data
  command: /nsqd --data-path=/data --lookupd-tcp-address=nsqlookupd:4160
  links:
    - nsqlookupd
  ports:
    - "4150:4150"
    - "4151:4151"

makedata:
  image: golang:1.5-wheezy
  volumes:
    - /go/src

make:
  image: golang:1.5-wheezy
  volumes_from: 
    - makedata
  volumes: 
    - ./:/go/src/github.com/briandowns/aion
  working_dir: /go/src/github.com/briandowns/aion
  entrypoint: /usr/bin/make
  command: dep build

aion:
  build: docker
  links:
    - db
    - nsqd
  volumes:
    - ./:/opt/aion:ro
  working_dir: /opt/aion
  ports:
    - "9898:9898"
